export default {
  apple: require("./apple.png"),
  ArrowLeft: require("./ArrowLeft.png"),
  ArrowBack: require("./ArrowBack.png"),
  box: require("./box.png"),
  check: require("./check.png"),
  Eye: require("./Eye.png"),
  fb: require("./facebook.png"),
  google: require("./google.png"),
  email: require("./email.png"),
  bars: require("./bars.png"),
  bell: require("./bell.png"),
  logo: require("./logo.png"),
  arrowRight: require("./arrowRight.png"),
  Home: require("./Home.png"),
  Heart: require("./Heart.png"),
  Cart: require("./Cart.png"),
  Categories: require("./Categories.png"),
  Orders: require("./Orders.png"),
  visa: require("./visa.png"),
  visa2: require("./visa2.png"),
  ArrowDown: require("./ArrowDown.png"),
  Tuning: require("./Tuning.png"),
  Magnifer: require("./Magnifer.png"),
  Share: require("./Share.png"),
  CartPlus: require("./CartPlus.png"),
};
